[ai]
ai_similarity_enabled = false
ai_similarity_keywords = ""

[settings]
allow_nsfw = false
theme = "dark"
times_to_run = 1
opacity = 0.9
storymode = false
storymodemethod = 1
storymode_max_length = 1000
resolution_w = 1080
resolution_h = 1920
zoom = 1.0

[settings.background]
background_video = "minecraft"
background_audio = "lofi"
background_audio_volume = 0.15
enable_extra_audio = false
background_thumbnail = false
background_thumbnail_font_family = "arial"
background_thumbnail_font_size = 96
background_thumbnail_font_color = "255,255,255"

[settings.tts]
random_voice = true
elevenlabs_voice_name = "Adam"
elevenlabs_api_key = "c8a9f5b8164281ae72f0e948d2e4ebc6"
aws_polly_voice = "Matthew"
streamlabs_polly_voice = "Matthew"
tiktok_voice = "en_us_001"
tiktok_sessionid = "00988cd5e4e4f020d97866e667efcb8d"
python_voice = "1"
py_voice_num = "2"
silence_duration = 0.3
no_emojis = false
voice_choice = "streamlabspolly"

[reddit.creds]
client_id = "K5HSvUldgCzabInZVIwa7Q"
client_secret = "xXGFYbvp3HguhyiKJ-7xUaWXWoSbng"
username = "RqZen187"
password = "!Sebastian2007"
2fa = false

[reddit.thread]
random = false
subreddit = "funnystories+stories+AskReddit+Redditdev"
post_id = ""
max_comment_length = 500
min_comment_length = 1
post_lang = ""
min_comments = 20
